-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["Object-BranchL1@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -61, -17  ,  -72, -3  ,  -157, 26  ,  -157, -4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   143, 1  ,  139, 5  ,  97, 13  ,  41, 16  ,  51, 2  ,  138, -9  ,  144, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   41, 16  ,  21, 16  ,  12, 2  ,  51, 2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -61, -17  ,  12, 2  ,  -72, -3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -58, -2  ,  12, 2  ,  21, 16  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-BranchL2@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -162, -24  ,  -64, -36  ,  -142, 3  ,  -162, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   155, -13  ,  150, -9  ,  45, 1  ,  103, -24  ,  149, -29  ,  156, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   46, 28  ,  37, 29  ,  21, 0  ,  25, -17  ,  45, 1  ,  53, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -64, -36  ,  -57, -18  ,  -142, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   0, -20  ,  21, 0  ,  -57, -18  ,  -64, -36  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   25, -17  ,  21, 0  ,  0, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   103, -24  ,  45, 1  ,  25, -17  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-BranchL3@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   155, -21  ,  154, -10  ,  110, -3  ,  45, 2  ,  100, -24  ,  139, -30  ,  153, -28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -162, -25  ,  -68, -36  ,  -46, -33  ,  -63, -18  ,  -162, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   45, 2  ,  48, -19  ,  100, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   45, 2  ,  19, 1  ,  -63, -18  ,  48, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   49, 28  ,  38, 30  ,  19, 1  ,  45, 2  ,  55, 23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -63, -18  ,  -46, -33  ,  11, -19  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-BranchR1@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -131, -11  ,  -108, -9  ,  -44, -1  ,  -15, 14  ,  -54, 15  ,  -137, 7  ,  -142, 1  ,  -142, -9  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   162, 28  ,  61, -2  ,  65, -19  ,  162, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   61, -2  ,  -15, 14  ,  19, -8  ,  65, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -15, 14  ,  -15, 0  ,  19, -8  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -15, 14  ,  -44, -1  ,  -15, 0  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-BranchR2@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -149, -29  ,  -40, -18  ,  -43, 1  ,  -109, -4  ,  -151, -10  ,  -156, -15  ,  -156, -25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   63, -19  ,  43, -31  ,  65, -36  ,  162, -24  ,  162, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -54, 18  ,  -43, 1  ,  -7, -18  ,  -20, 1  ,  -45, 29  ,  -51, 26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -7, -18  ,  -43, 1  ,  -40, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -45, 29  ,  -20, 1  ,  -38, 29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   63, -19  ,  -20, 1  ,  -7, -18  ,  43, -31  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-BranchR3@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -153, -30  ,  -133, -29  ,  -86, -22  ,  -45, 0  ,  -92, -1  ,  -139, -7  ,  -155, -11  ,  -158, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -40, -19  ,  -45, 0  ,  -86, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -20, -18  ,  -19, 0  ,  -40, 32  ,  -45, 0  ,  -40, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   62, -17  ,  62, -37  ,  161, -25  ,  161, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -55, 20  ,  -45, 0  ,  -40, 32  ,  -51, 28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   4, -23  ,  62, -17  ,  -19, 0  ,  -20, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   62, -37  ,  62, -17  ,  4, -23  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-LedgeL1@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -163, -43  ,  156, -43  ,  -40, 22  ,  -163, 31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   108, -21  ,  156, -43  ,  144, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -40, 22  ,  27, 1  ,  -3, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   27, 1  ,  108, -21  ,  91, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   27, 1  ,  156, -43  ,  108, -21  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-LedgeL2@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -162, -37  ,  -91, 27  ,  -162, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   107, -17  ,  146, -38  ,  141, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -162, -37  ,  146, -38  ,  25, 5  ,  -40, 24  ,  -91, 27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -40, 24  ,  25, 5  ,  2, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   25, 5  ,  146, -38  ,  91, -9  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-LedgeR1@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   43, 22  ,  0, 14  ,  -117, -43  ,  162, -43  ,  162, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -117, -43  ,  -110, -19  ,  -146, -24  ,  -157, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -117, -43  ,  -25, 2  ,  -84, -10  ,  -110, -19  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-LedgeR2@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   94, 27  ,  162, -37  ,  162, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -147, -38  ,  -104, -17  ,  -141, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   40, 24  ,  -147, -38  ,  162, -37  ,  94, 27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -22, 5  ,  40, 24  ,  2, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -147, -38  ,  -22, 5  ,  -85, -8  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-Outcrop1@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   39, -1  ,  -1, 25  ,  -27, 17  ,  -1, -25  ,  24, -28  ,  49, -25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -25, -28  ,  -1, -25  ,  -27, 17  ,  -45, 0  ,  -52, -26  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-Outcrop2@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   40, 0  ,  -3, 27  ,  -27, 19  ,  1, -27  ,  24, -31  ,  51, -27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -22, -30  ,  1, -27  ,  -27, 19  ,  -45, 0  ,  -53, -27  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-Outcrop4@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   41, 1  ,  -1, 28  ,  -28, 21  ,  -2, -27  ,  23, -31  ,  52, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -27, -30  ,  -2, -27  ,  -28, 21  ,  -46, 3  ,  -54, -26  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-Outcrop5@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -38, -1  ,  -48, 26  ,  -51, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   47, 26  ,  -48, 26  ,  -38, -1  ,  48, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -23, -21  ,  -14, -28  ,  -2, -30  ,  11, -27  ,  24, -19  ,  35, -2  ,  -38, -1  }
                    }
                    
                    
                    
		}
		
		, 
		["Object-Outcrop6@2x"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   47, 27  ,  -48, 28  ,  -34, -3  ,  35, -3  ,  51, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -34, -3  ,  -48, 28  ,  -50, -3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 33, groupIndex = 0 },
                    shape = {   -17, -21  ,  -7, -26  ,  9, -26  ,  22, -18  ,  35, -3  ,  -34, -3  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

